# .github/workflows/deploy.yml
name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  APP_ID: shirtbot
  RUN_REGION: us-central1
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  SHIRT_POROCESSING_ADDRESS: ${{ secrets.SHIRT_POROCESSING_ADDRESS }}
  CONFIG_FILE: config.yaml
  SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: $WORKLOAD_IDENTITY_PROVIDER
          service_account: $SERVICE_ACCOUNT

      - name: Setup
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: $PROJECT_ID

      - name: Build
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA

      - id: 'deploy'
        name: Deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: $APP_ID
          image: gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA
          project_id: $PROJECT_ID
          env_vars: TOKEN=$TELEGRAM_TOKEN,SHIRT_POROCESSING_ADDRESS=$SHIRT_POROCESSING_ADDRESS,CONFIG_FILE=$CONFIG_FILE
          
      - name: Link
        run: curl "https://api.telegram.org/bot${TELEGRAM_TOKEN}/setWebhook?url=${{ steps.deploy.outputs.url }}"
