# .github/workflows/deploy.yml
name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  APP_ID: shirtbot
  RUN_REGION: us-central1
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  SHIRT_POROCESSING_ADDRESS: ${{ secrets.SHIRT_POROCESSING_ADDRESS }}
  CONFIG_FILE: config.yaml

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: $PROJECT_ID

      - name: Build
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA

      - name: Deploy
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: $APP_ID
          image: gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA
          project_id: $PROJECT_ID
          env_vars: TOKEN=$TELEGRAM_TOKEN,SHIRT_POROCESSING_ADDRESS=$SHIRT_POROCESSING_ADDRESS,CONFIG_FILE=$CONFIG_FILE
          
      - name: Link
        run: curl "https://api.telegram.org/bot${TELEGRAM_TOKEN}/setWebhook?url=${{ steps.deploy.outputs.url }}"
